version: 2.1
jobs:
  build:
    working_directory: ~/speedlify-circleci
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Add git user
          command: |
            git config user.email "bot@github.com"
            git config user.name "Bot"
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn/cache
            - ~/.yarn/unplugged
      - run:
          name: Build production
          command: yarn build-production
      - add_ssh_keys:
          fingerprints:
            - '21:db:d2:a3:02:84:d7:53:44:9d:d5:10:f3:2b:19:69'
      - run:
          name: Add known hosts
          command: |
            mkdir -p ~/.ssh
            echo ${GITHUB_KNOWN_HOST} >> ~/.ssh/known_hosts
      - run:
          name: Push new files
          command: |
            git add _data _site
            git commit -m "[skip ci] deploy new _data and _site"
            git push origin main
      - run:
          name: Deploy _site to GH Pages
          command: |
            npm install --prefix=$HOME/.local --global gh-pages
            gh-pages --dotfiles --message "[skip ci] new site version" --dist _site

workflows:
  version: 2
  load-legacy-db:
    jobs:
      - build
    triggers:
      - schedule:
          cron: '0 0/2 * 1/1 * ? *'
          filters:
            branches:
              only:
                - master
